name: PRs reviews reminder

on:
  schedule:
    - cron: "0 8-23/3 * * 1-5"

jobs:
  pr-reviews-reminder:
    runs-on: ubuntu-latest
    steps:
      - uses: davideviolante/pr-reviews-reminder-action@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          webhook-url: 'https://hooks.slack.com/services/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' # Required
          provider: 'slack' # Required (slack or msteams)
          channel: '#coding-test-github' # Optional, eg: #general
          github-provider-map: '' # Optional, eg: "DavideViolante:UEABCDEFG,foobar:UAABCDEFG"